stages:
- check
- build
- release

black-lint:
  image: python:3.9
  stage: check
  script:
  - pip install black
  - black --check .

flake8-lint:
  image: python:3.9
  stage: check
  script:
  - pip install flake8 flake8-black
  - flake8 .

mypy-lint:
  image: python:3.9
  stage: check
  script:
  - pip install mypy
  - mypy . --install-types --non-interactive --ignore-missing-imports

pytest-py38:
  image: python:3.8
  stage: check
  script:
  - pip install poetry
  - poetry install
  - >
    poetry run
    py.test
    --verbose
    --cov-report term-missing
    --cov=hacksaws
    .
  artifacts:
    paths:
    - .coverage
    - coverage.xml
    expire_in: 1 day

pytest-py39:
  image: python:3.9
  stage: check
  coverage: '/^TOTAL.*\s+\d+\s+\d+\s+(\d+)%/'
  script:
  - pip install poetry
  - poetry install
  - >
    poetry run
    py.test
    --verbose
    --cov-report term-missing
    --cov=hacksaws
    .
  artifacts:
    paths:
    - .coverage
    - coverage.xml
    expire_in: 1 day

build-library:
  image: python:3.9
  stage: build
  script:
  - pip install poetry
  - poetry build
  artifacts:
    paths:
    - dist/
    expire_in: 90 days
  rules:
  - if: $CI_PROJECT_NAMESPACE == "rocket-boosters" && $CI_COMMIT_TAG

publish-library:
  image: python:3.9
  stage: release
  script:
  - pip install poetry
  - poetry publish -u "${PYPI_USER}" -p "${PYPI_HACKSAWS_PAT}"
  rules:
  - if: $CI_PROJECT_NAMESPACE == "rocket-boosters" && $CI_COMMIT_TAG
